function populate(s1,s2){
var s1=document.getElementById(s1);
var s2=document.getElementById(s2);

s2.innerHTML="";

if(s1.value=="ANDAMAN AND NICOBAR ISLAND "){
var optionArray=['NICOBAR','NORTH AND MIDDLE ANDAMAN','SOUTH ANDAMAN'];
}
else if(s1.value=='ANDHRA PRADESH'){
var optionArray=['ANANTAPUR','CHITTOOR','EAST GODAVARI','GUNTUR','KRISHNA','KURNOOL','MAHBUBNAGAR','PRAKASAM','SRIKAKULAM',
'SRI POTTI SRIRAMULU NELLORE','VISAKHAPATNAM','VIZIANAGARAM','WARANGAL','WEST GODAVARI','YSR DISTRICT, KADAPA (CUDDAPAH)'];
}
else if(s1.value=='ARUNACHAL PRADESH'){
var optionArray=['ANJAW','CHANGLANG','DIBANG VALLEY','EAST KAMENG','EAST SIANG','KAMLE','KRA DAADI','KURUNG KUMEY','LEPA RADA','LOHIT',
'LONGDING','LOWER DIBANG VALLEY','LOWER SIANG','LOWER SUBANSIRI','NAMSAI','PAKKE KESSANG','PAPUM PARE','SHI YOMI','SIANG','TAWANG','TIRAP','UPPER SIANG',
'UPPER SUBANSIRI','WEST KAMENG','WEST SIANG'];
}

else if(s1.value=='ASSAM'){
var optionArray=['BAKSA','BARPETA','BISWANATH','BONGAIGAON','CACHAR','CHARAIDEO','CHIRANG','DARRANG','SOUTH SALAMARA-MANKACHAR',
'DHEMAJI','DHUBRI','DIBRUGARH','DIMA HASAO (NORTH CACHAR HILLS)','GOALPARA','GOLAGHAT','HAILAKANDI','HOJAI','JORHAT','KAMRUP',
'KAMRUP METROPOLITAN','TINSUKIA','UDALGURI','KARBI ANGLONG','KARIMGANJ','WEST KARBI ANGLONG','KOKRAJHAR','LAKHIMPUR','MAJULI','MORIGAON','NAGAON','NALBARI','SIVASAGAR','SONITPUR',];
}

else if(s1.value=='BIHAR'){
var optionArray=['ARARIA','ARWAL','AURANGABAD','BANKA','BEGUSARAI','BHAGALPUR','BHOJPUR','BUXAR','DARBHANGA','EAST CHAMPARAN',
'GAYA','GOPALGANJ','JAMUI','JEHANABAD','KAIMUR','KATIHAR','KHAGARIA','KISHANGANJ','LAKHISARAI','MADHEPURA','MADHUBANI',
'MUNGER','MUZAFFARPUR','NALANDA','NAWADA','PATNA','PURNIA','ROHTAS','SAHARSA','SAMASTIPUR','SARAN','SHEIKHPURA','SHEOHAR','SITAMARHI','SIWAN','SUPAUL','VAISHALI','WEST CHAMPARAN'];
}

else if(s1.value=='CHANDIGARH'){
var optionArray=['CHANDIGARH'];
}

else if(s1.value=='CHHATTISGARH'){
var optionArray=['BALOD','BALODA BAZAR','BALRAMPUR','BASTAR','BEMETARA','BIJAPUR','BILASPUR','DANTEWADA','DHAMTARI',
'DURG','GARIYABAND','JANJGIR-CHAMPA','JASHPUR','KAWARDHA','KANKER','KONDAGAON','KORBA','KOREA','MAHASAMUND','MUNGELI','NARAYANPUR','RAIGARH]','RAIPUR','RAJNANDGAON','SUKMA','SURAJPUR','SURGUJA',];
}

else if(s1.value=='DADRA & NAGAR HAVELI'){
var optionArray=['DADRA & NAGAR HAVELI'];
}
else if(s1.value=='DAMAN AND DIU'){
var optionArray=['DAMAN','DIU'];
}

else if(s1.value=='DELHI'){
var optionArray=['DELHI'];
}
else if(s1.value=='GOA'){
var optionArray=['NORTH GOA','SOUTH GOA'];
}
else if(s1.value=='GUJARAT'){
var optionArray=['AHMEDABAD','AMRELI','ANAND','ARAVALLI','BANASKANTHA','BHARUCH','BHAVNAGAR','BOTAD','CHHOTA UDEPUR','DAHOD','DANGS','DEVBHOOMI DWARKA','GANDHINAGAR','GIR SOMNATH','JAMNAGAR','JUNAGADH','KACHCHH','KHEDA','MAHISAGAR','MEHSANA',
'MORBI','NARMADA','NAVSARI','PANCHMAHAL','PATAN','PORBANDAR','RAJKOT','SABARKANTHA','SURAT','SURENDRANAGAR','TAPI','VADODARA','VALSAD'];
}
else if(s1.value=='HARYANA'){
var optionArray=['AMBALA','BHIWANI','CHARKHI DADRI','FARIDABAD','FATEHABAD','GURGAON','HISAR','JHAJJAR','JIND','KAITHAL','KARNAL','KURUKSHETRA','MAHENDRAGARH','NUH','PALWAL','PANCHKULA','PANIPAT','REWARI','ROHTAK','SIRSA','SONIPAT','YAMUNANAGAR'];
}
else if(s1.value=='HIMACHAL PRADESH'){
var optionArray=['BILASPUR','CHAMBA','HAMIRPUR','KANGRA','KINNAUR','KULLU','LAHAUL & SPITI','MANDI','SHIMLA','SIRMAUR','SOLAN','UNA'];
}
else if(s1.value=='JAMMU AND KASHMIR'){
var optionArray=['ANANTNAG','AWANTIPORA','BANDIPORA','BARAMULA','BUDGAM','DODA','GANDERBAL','HANDWARA','JAMMU','KATHUA','KISHTWAR','KULGAM','KUPWARA','POONCH','PULWAMA','RAJOURI','RAMBAN','REASI','SAMBA','PUNCH','RIASI','SHOPIAN','SOPORE','SRINAGAR','UDHAMPUR'];
}
else if(s1.value=='JHARKHAND'){
var optionArray=['BOKARO','CHATRA','DEOGHAR','DHANBAD','DUMKA','EAST SINGHBHUM','GARHWA','GIRIDIH','GODDA','GUMLA','HAZARIBAG','JAMTARA','KHUNTI','KODERMA','LATEHAR','LOHARDAGA','PAKUR','PALAMU','RAMGARH','RANCHI','SAHIBGANJ','SERAIKELA-KHARSAWAN','SIMDEGA','WEST SINGHBHUM'];
}
else if(s1.value=='KARNATAKA'){
var optionArray=['BAGALKOT','BALLARI','BELAGAVI','BENGALURU (BANGALORE) RURAL','BENGALURU (BANGALORE) URBAN','BIDAR','CHAMARAJANAGAR','CHIKBALLAPUR','CHIKKAMAGALURU (CHIKMAGALUR)','CHITRADURGA','DAKSHINA KANNADA','DAVANGERE','DHARWAD','GADAG','HASSAN','HAVERI','KALABURAGI','KODAGU','KOLAR','KOPPAL','MANDYA','MYSURU (MYSORE)','RAICHUR','RAMANAGARA',
'SHIVAMOGGA (SHIMOGA)','TUMAKURU (TUMKUR)','UDUPI','UTTARA KANNADA (KARWAR)','VIJAYAPURA','YADGIR'];
}
else if(s1.value=='KERALA'){
var optionArray=['ALAPPUZHA','ERNAKULAM','IDUKKI','KANNUR','KASARAGOD','KOLLAM','KOTTAYAM','KOZHIKODE','MALAPPURAM','PALAKKAD','PATHANAMTHITTA','THIRUVANANTHAPURAM','THRISSUR','WAYANAD'];
}
else if(s1.value=='LADAKH'){
var optionArray=['KARGIL','LEH (LADAKH)'];
}
else if(s1.value=='LAKSHADWEEP'){
var optionArray=['KAVARATTI'];
}
else if(s1.value=='MADHYA PRADESH'){
var optionArray=['AGAR MALWA','ALIRAJPUR','ANUPPUR','ASHOKNAGAR','BALAGHAT','BARWANI','BETUL','BHIND','BHOPAL','BURHANPUR','CHHATARPUR','CHHINDWARA','DAMOH','DATIA','DEWAS','DHAR','DINDORI','GUNA','GWALIOR','HARDA','HOSHANGABAD',
'INDORE','JABALPUR','JHABUA','KATNI','KHANDWA','KHARGONE','MANDLA','MANDSAUR','MORENA','NARSINGHPUR','NEEMUCH','PANNA','RAISEN','RAJGARH','RATLAM','REWA','SAGAR','SATNA','SEHORE','SEONI','SHAHDOL','SHAJAPUR','SHEOPUR','SHIVPURI','SIDHI','SINGRAULI','TIKAMGARH','UJJAIN','UMARIA','VIDISHA'];
}
else if(s1.value=='MAHARASHTRA'){
var optionArray=['AHMEDNAGAR','AKOLA','AMRAVATI','AURANGABAD','BEED','BHANDARA','BULDHANA','CHANDRAPUR','DHULE','GADCHIROLI','GONDIA','HINGOLI','JALGAON','JALNA','KOLHAPUR','LATUR','MUMBAI CITY','MUMBAI SUBURBAN',
'NAGPUR','NANDED','NANDURBAR','NASHIK','OSMANABAD','PALGHAR','PARBHANI','PUNE','RAIGAD','RATNAGIRI','SANGLI','SATARA','SINDHUDURG','SOLAPUR','THANE','WARDHA','WASHIM','YAVATMAL'];
}
else if(s1.value=='MANIPUR'){
var optionArray=['BISHNUPUR','CHANDEL','CHURACHANDPUR','IMPHAL EAST','IMPHAL WEST','JIRIBAM','KAKCHING','KAMJONG','KANGPOKPI','NONEY','PHERZAWL','SENAPATI','TAMENGLONG','TENGNOUPAL','THOUBAL','UKHRUL'];
}
else if(s1.value=='MEGHALAYA'){
var optionArray=['EAST GARO HILLS','EAST KHASI HILLS','NORTH GARO HILLS','RI BHOI','SOUTH GARO HILLS','SOUTH WEST GARO HILLS','SOUTH WEST KHASI HILLS','WEST GARO HILLS','JAINTIA HILLS','WEST KHASI HILLS'
];
}
else if(s1.value=='MIZORAM'){
var optionArray=['AIZAWL','CHAMPHAI','KOLASIB','LAWNGTLAI','LUNGLEI','MAMIT','SAIHA','SERCHHIP'];
}
else if(s1.value=='NAGALAND'){
var optionArray=['DIMAPUR','KIPHIRE','KOHIMA','LONGLENG','MOKOKCHUNG','MON','PEREN','PHEK','TUENSANG','WOKHA','ZUNHEBOTO'];
}
else if(s1.value=='ODISHA'){
var optionArray=['ANGUL','BALANGIR','BALASORE','BARGARH','BHADRAK','BOUDH','CUTTACK','DEOGARH','DHENKANAL','GAJAPATI','GANJAM','JAGATSINGHAPUR','JAJPUR','JHARSUGUDA','KALAHANDI','KANDHAMAL','KENDRAPARA','KENDUJHAR (KEONJHAR)','KHORDHA',
'KORAPUT','MALKANGIRI','MAYURBHANJ','NABARANGPUR','NAYAGARH','NUAPADA','PURI','RAYAGADA','SAMBALPUR','SONEPUR','SUNDARGARH'];
}
else if(s1.value=='PUDUCHERRY'){
var optionArray=['PUDUCHERRY','KARAIKAL','MAHE','YANAM'];
}
else if(s1.value=='PUNJAB'){
var optionArray=['AMRITSAR','BARNALA','BATHINDA','FARIDKOT','FATEHGARH SAHIB','FAZILKA','FEROZEPUR','GURDASPUR','HOSHIARPUR',
'JALANDHAR','KAPURTHALA','LUDHIANA','MANSA','MOGA','MUKTSA','NAWANSHAHR (SHAHID BHAGAT SINGH NAGAR)','PATHANKOT','PATIALA','RUPNAGAR','MOHALI','SANGRUR','TARN TARAN'];
}
else if(s1.value=='RAJASTHAN'){
var optionArray=['AJMER','ALWAR','BANSWARA','BARAN','BARMER','BHARATPUR','BHILWARA','BIKANER','BUNDI','CHITTORGARH','CHURU','DAUSA','DHOLPUR','DUNGARPUR','HANUMANGARH','JAIPUR','JAISALMER','JALORE','JHALAWAR','JHUNJHUNU','JODHPUR',
'KARAULI','KOTA','NAGAUR','PALI','PRATAPGARH','RAJSAMAND','SAWAI MADHOPUR','SIKAR','SIROHI','SRI GANGANAGAR','TONK','UDAIPUR'];
}
else if(s1.value=='SIKKIM'){
var optionArray=['EAST SIKKIM','NORTH SIKKIM','SOUTH SIKKIM','WEST SIKKIM'];
}
else if(s1.value=='TAMIL NADU'){
var optionArray=['ARIYALUR','CHENGALPATTU','CHENNAI','COIMBATORE','CUDDALORE','DHARMAPURI','DINDIGUL','ERODE','KALLAKURICHI','KANCHIPURAM','KANYAKUMARI','KARUR','KRISHNAGIRI','MADURAI','NAGAPATTINAM','NAMAKKAL','NILGIRIS','PERAMBALUR','PUDUKKOTTAI',
'RAMANATHAPURAM','RANIPET','SALEM','SIVAGANGA','TENKASI','THANJAVUR','THENI','THOOTHUKUDI (TUTICORIN)','TIRUCHIRAPPALLI','TIRUNELVELI','TIRUPATHUR','TIRUPPUR','TIRUVALLUR','TIRUVANNAMALAI','TIRUVARUR','VELLORE','VILUPPURAM','VIRUDHUNAGAR'];
}
else if(s1.value=='TELANGANA'){
var optionArray=['ADILABAD','BHADRADRI KOTHAGUDEM','HYDERABAD','JAGTIAL','JANGAON','JAYASHANKAR BHOOPALPALLY','JOGULAMBA GADWAL','KAMAREDDY','KARIMNAGAR','KHAMMAM','KOMARAM BHEEM ASIFABAD',
'MAHABUBABAD','MAHABUBNAGAR','MANCHERIAL','MEDAK','MEDCHAL','NAGARKURNOOL','NALGONDA','NIRMAL','NIZAMABAD','PEDDAPALLI','RAJANNA SIRCILLA','RANGAREDDY','SANGAREDDY','SIDDIPET','SURYAPET','VIKARABAD','WANAPARTHY','WARANGAL (RURAL)','WARANGAL (URBAN)','YADADRI BHUVANAGIRI'];
}
else if(s1.value=='TRIPURA'){
var optionArray=['DHALAI','GOMATI','KHOWAI','NORTH TRIPURA','SEPAHIJALA','SOUTH TRIPURA','UNAKOTI','WEST TRIPURA'];
}
else if(s1.value=='UTTARAKHAND'){
var optionArray=['ALMORA','BAGESHWAR','CHAMOLI','CHAMPAWAT','DEHRADUN','HARIDWAR','NAINITAL','PAURI GARHWAL','PITHORAGARH','RUDRAPRAYAG','TEHRI GARHWAL','UDHAM SINGH NAGAR','UTTARKASHI'];
}
else if(s1.value=='UTTAR PRADESH'){
var optionArray=['AGRA','ALIGARH','ALLAHABAD','AMBEDKAR NAGAR','AMETHI (CHATRAPATI SAHUJI MAHRAJ NAGAR)','AMROHA (J.P. NAGAR)','AURAIYA','AZAMGARH','BAGHPAT','BAHRAICH','BALLIA','BALRAMPUR','BANDA','BARABANKI','BAREILLY','BASTI','BHADOHI','BIJNOR','BUDAUN','BULANDSHAHR','CHANDAULI','CHITRAKOOT','DEORIA','ETAH','ETAWAH','FAIZABAD','FARRUKHABAD','FATEHPUR','FIROZABAD','GAUTAM BUDDHA NAGAR',
'GHAZIABAD','GHAZIPUR','GONDA','GORAKHPUR','HAMIRPUR','HAPUR (PANCHSHEEL NAGAR)','HARDOI','HATHRAS','JALAUN','JAUNPUR','JHANSI','KANNAUJ','KANPUR DEHAT','KANPUR NAGAR','KANSHIRAM NAGAR (KASGANJ)','KAUSHAMBI','KUSHINAGAR (PADRAUNA)','KHERI',
'LALITPUR','LUCKNOW','MAHARAJGANJ','MAHOBA','MAINPURI','MATHURA','MAU','MEERUT','MIRZAPUR','MORADABAD','MUZAFFARNAGAR','PILIBHIT','PRATAPGARH','RAEBARELI','RAMPUR','SAHARANPUR','SAMBHAL (BHIM NAGAR)','SANT KABIR NAGAR','SHAHJAHANPUR',
'SHAMALI (PRABUDDH NAGAR)','SHRAVASTI','SIDDHARTH NAGAR','SITAPUR','SONBHADRA','SULTANPUR','UNNAO','VARANASI'];
}
else if(s1.value=='WEST BENGAL'){
var optionArray=['ALIPURDUAR','BANKURA','BIRBHUM','COOCH BEHAR','DAKSHIN DINAJPUR (SOUTH DINAJPUR)','DARJEELING','HOOGHLY',
'HOWRAH','JALPAIGURI','JHARGRAM','KALIMPONG','KOLKATA','MALDA','MURSHIDABAD','NADIA','NORTH 24 PARGANAS','PASCHIM MEDINIPUR (WEST MEDINIPUR)','BARDHAMAN','PURBA MEDINIPUR (EAST MEDINIPUR)','PURULIA','SOUTH 24 PARGANAS','UTTAR DINAJPUR (NORTH DINAJPUR)'];
}


for(var option in optionArray){
var pair=optionArray[option];
var newoption=document.createElement("option");

newoption.value=pair;
newoption.innerHTML=pair;
s2.options.add(newoption);
}

}
