# Generated by Django 4.1.2 on 2022-11-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
